---
title: "Thoughts on Programming"
author: "J. Huband"
date: "February 18, 2021"
output: 
  html_document:
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Programming in General

Programming is like creating a recipe -- you start with a list of ingredients (data) and give the computer a list of instructions, telling it exactly what to do with the ingredients. Each step must be clear, precise, and lead to the final product.  

But, instead of a delicious cake or pie as the outcome, the product will be a solution to a problem or, perhaps a set of results that you can interpret later.  A program, like a recipe, should produce the same output when given the same ingredients and instructions.


Computers are very limited in what they can understand. Your set of instructions must be written in a language that the computer can follow. For this workshop, that language will be R.

### R as a Programming Language

As a language, R has a syntax and a grammar. Unlike most natural lnaguages, it has very strict rules for following the syntax. The strict rules  ensure that we are precise in telling the computer what to do.

Learning R means that you must learn

i) the rules of the language, and 

ii) how to translate your thoughts (i.e., instuctions for what needs to be done) into that language. 

This second step takes lots of practice. You may not get the instructions right on the first try (or even the second or third try).  But, you will get better with practice.

### Logic and Testing

R is an **interpretive** language. The computer will interpret each statement, and follow the instructions required by that statement, before moving on to the next statement.  So, the set of instructions must have a logical flow.  For example, the computer cannot analyze data until it reads in the data.

We also must ensure that the instructions are correct. If we intend to add two number but give the instruction to multiply the two the two numbers, we are giving an incorrect instruction.  The computer will perform the operation even if it is not what you intended.

We can verify the logic and correctness of our instructions by testing the code as we write it.  It helps to start with an outline of the tasks that you want to computer to do. Then, you type the code for each task, you can test it with simple inputs -- values for which we can know what the outcomes should be.  

Testing our code in this manner gives us more confidence that the code works correctly, but for any program of significant length, we cannot guarantee that our code will work 100% of the time.


 

The beauty of programming is that once you have a tested set of instructions, you can reproduce the work that it has done. As you know, **reproducibility** is important for publications.  But more importantly, if your program is written to work on a general set of data (instead of a specific set), then it is also **repeatable**.

Writing a program that is **generalized** will require more thought as you are designing your program, but it will save you time and effort if you can reuse the code for different sets of data.

