install.packages("tidyverse")
install.packages("rjson")
install.packages("RColorBrewer")
install.packages("tm")
install.packages("wordcloud")
install.packages("SnowballC")
install.packages("tidytext")
install.packages("sentimentr")
